#!/opt/homebrew/bin/bash

# Subset to the 11 agencies we want.

# AG-DEPARTMENT OF AGRICULTURE
# AG23-OFFICE OF THE INSPECTOR GENERAL
# DD-DEPARTMENT OF DEFENSE
# DD26-OFFICE OF THE INSPECTOR GENERAL
# ED-DEPARTMENT OF EDUCATION
# EDEF-OFFICE OF INSPECTOR GENERAL
# GS-GENERAL SERVICES ADMINISTRATION
# GS15-OFFICE OF INSPECTOR GENERAL
# HE-DEPARTMENT OF HEALTH AND HUMAN SERVICES
# HE13-OFFICE OF INSPECTOR GENERAL
# HS-DEPARTMENT OF HOMELAND SECURITY
# HSAE-OFFICE OF THE INSPECTOR GENERAL
# HU-DEPARTMENT OF HOUSING AND URBAN DEVELOPMENT
# HUGG-OFFICE OF INSPECTOR GENERAL
# DJ-DEPARTMENT OF JUSTICE
# DJ10-OFFICE OF THE INSPECTOR GENERAL
# DL-DEPARTMENT OF LABOR
# DLIG-OFFICE OF THE INSPECTOR GENERAL
# TD-DEPARTMENT OF TRANSPORTATION
# TD12-OFFICE OF INSPECTOR GENERAL
# TR-DEPARTMENT OF THE TREASURY
# TR95-OFFICE OF INSPECTOR GENERAL
# VA-DEPARTMENT OF VETERANS AFFAIRS
# VAAF-INSPECTOR GENERAL

sed -n '1p' data/data_files/full_data.txt > data/data_files/subset_data.txt
grep -E 'AG23|DD26|EDEF|GS15|HE13|HSAE|HUGG|DJ10|DLIG|TD12|TR95|VAAF' data/data_files/full_data.txt >> data/data_files/subset_data.txt # Faster than sed.
